### ISSUE TITLE
E-Mail Address can't stay empty/can't be removed

### ISSUE THREAD

**Issue by quelsh** [modoboa/modoboa-contacts#158]
I imported contacts from my Google Account. A lot of them don't have an e-mail address but only a phone number.

When I open a contact it shows with an empty e-mail address.
I cannot delete this e-mail address (not available) nor can I leave it empty (error message in the form), forcing me to use weird placeholder addresses to denote that it is not the actual address even if I just want to edit another property.

Is there a reason why the e-mail address can't be deleted or left empty?

**Comment by tonioo** [comment]
@quelsh The email field is currently the only required field when you create a contact. It was designed like this back in the days and I realize it was not necessarily a good idea but that's something we can change

**Comment by quelsh** [comment]
Thanks for the answer! I'd appreciate that change a lot 🙂
