### ISSUE TITLE
Auto compose the 'Full name'

### ISSUE THREAD

**Issue by tuxis-ie** [modoboa/modoboa-contacts#4]
When you add a new contact, compose the default 'Name' from 'First name' and 'Last name'.

**Comment by tonioo** [comment]
@tuxis-ie Not so easy to find what is the first name and what is the last name. How would you do it?

**Comment by tuxis-ie** [comment]
Well, from the input form? :)

**Comment by tuxis-ie** [comment]
![selection_066](https://cloud.githubusercontent.com/assets/2149624/26002978/b00e6b52-3731-11e7-9dd7-99a487d70163.png)

**Comment by tonioo** [comment]
Sorry, I was thinking about the add feature available from the webmail !

**Comment by tuxis-ie** [comment]
I don't see that ?

**Comment by tonioo** [comment]
Have you updated the webmail plugin to the latest version?

**Comment by tonioo** [comment]
yes, but don't forget to run the collectstatic command. When you're done, go to the webmail, open a message, you should see new buttons near email addresses to add them to your address book.

**Comment by tuxis-ie** [comment]
0 static files copied to '/srv/modoboa/instance/sitestatic', 2204 unmodified.
